resolution 
api = 1
cpu_mhz
#cpu_power
#gpu_power
ram
vram
#network
# Display miscellaneous information
#engine_version
#engine_short_names
#gpu_name
#vulkan_driver
#wine
#exec_name
#winesync
#present_mode
