foreground      #dfdfde
background      #0c0b0c
cursor          #dfdfde
 
color0          #f3f4f3
color8          #636364
color1          #7a7d81
color9          #7a7d81
color2          #7c807e
color10         #7c807e
color3          #707172
color11         #707172
color4          #596668
color12         #596668
color5          #4f5051
color13         #4f5051
color6          #3b4447
color14         #3b4447
color7          #dfdfde
color15         #dfdfde
