# Video output & performance
profile=fast        # stable playback
vo=gpu             # use GPU for drawing
#vo=drm             # this tells mpv to talk directly to DRM/KMS and take over the screen like it owns the place 
                   # in other words you can play videos from tty 
hwdec=auto           # disable hardware decoding
gpu-context=x11    # safe context on Wayland/Hyprland

# Fullscreen / window
fs=yes             # start fullscreen
keepaspect=yes     # maintain aspect ratio

# Subtitles
sub-auto=fuzzy
sub-font="/home/echo/.fonts/my-subtitles.ttf"   # replace with your font file path
sub-font-size=36
sub-border-size=2
sub-shadow-offset=2
sub-ass-style=Default
sub-file-paths=~/Videos/sub          # directory with subtitle files

# Looping & playback
loop-file=no       # yes to loop videos
save-position-on-quit=yes

