foreground      #bcbfce 
background      #0f0f17 
cursor          #bcbfce 

color0          #0f0f17
color1          #63667C
color2          #636A86         
color3          #70748B
color4          #8A798B
color5          #7C829C
color6          #9E8FA1
color7          #bcbfce
color8          #838590
color9          #63667C
color10         #636A86 
color11         #70748B 
color12         #8A798B 
color13         #7C829C 
color14         #9E8FA1 
color15         #bcbfce 
