# Include pywal colors
#include ~/.cache/wal/colors-kitty.conf
include ~/.config/kitty/colors.conf
shell_integration no_cursor

font_family  Fira Code SemiBold 
#font_family Noto Sans Mono Arabic  
#System-UiBold 
#Terminus(TTF) 
bold_font        auto
font_size  16.0
#font_size  11.0
#11.0.5
cursor_trail 1 
# cursor animation
#background_opacity 0.8 
background_opacity 0.7 
dynamic_background_opacity = yes
#0.5.7
#disable_ligatures always
#adjust_line_height 0.5
#adjust_column_width 0.5
#bold_italic_font auto
enable_audio_bell no
window_padding_width 20.5

# enable remote contorl.
allow_remote_control yes
# always use split layouts.
enabled_layouts splits
startup_layout splits

# custom keybinds for spliting window.
map alt+shift+v launch --location=vsplit 

# custom cursor
cursor_shape block
cursor_beam_thickness  4 

# BEGIN_KITTY_THEME
# Batman
# Batman.conf
# Desert.conf
#include current-theme.conf
# END_KITTY_THEME


# BEGIN_KITTY_FONTS
# END_KITTY_FONTS


